package catalog_test

import (
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"

	"github.com/bhaktiyudha/bykami/agent/internal/catalog"
)

func TestAllPackagesValidate(t *testing.T) {
	all, err := catalog.All()
	if err != nil {
		t.Fatalf("catalog: %v", err)
	}
	if len(all) == 0 {
		t.Fatal("the booth has nothing to sell")
	}

	seen := map[string]bool{}
	for _, p := range all {
		if seen[p.ID] {
			t.Fatalf("duplicate package id %q", p.ID)
		}
		seen[p.ID] = true
	}
}

func TestGet(t *testing.T) {
	p, err := catalog.Get("mini")
	if err != nil {
		t.Fatalf("get: %v", err)
	}
	if p.Name != "Single Session" {
		t.Fatalf("name = %q", p.Name)
	}
	if _, err := catalog.Get("not-a-package"); err == nil {
		t.Fatal("returned a package that does not exist")
	}
}

// The booth has no price list, so the server has to know what it is selling
// without being told. A catalogue that grew a second package would make the
// kiosk sell whichever one happened to be first.
func TestOnlyIsTheOnePackageTheBoothSells(t *testing.T) {
	only, err := catalog.Only()
	if err != nil {
		t.Fatalf("only: %v", err)
	}

	all, err := catalog.All()
	if err != nil {
		t.Fatalf("catalog: %v", err)
	}
	if len(all) != 1 {
		t.Fatalf("the booth sells %d packages; the kiosk can only offer one", len(all))
	}
	if only.ID != all[0].ID {
		t.Fatalf("Only returned %q, catalogue holds %q", only.ID, all[0].ID)
	}
	if only.PrintCopies != 1 {
		// Everything past the first sheet is a paid reprint. A session that
		// included two would hand the second one out for free.
		t.Fatalf("print_copies = %d, want the single included print", only.PrintCopies)
	}
	if only.DurationMinutes <= 0 {
		// The kiosk counts this down on the capture screen; zero would expire
		// the photo session the moment the camera opened.
		t.Fatal("the session has no duration for the capture screen to count down")
	}
}

// The drift guard.
//
// packages/content/src/verticals/studio.ts is the source of truth for prices,
// and this package copies them because a Go binary on an offline Windows PC
// cannot read TypeScript. A price changed there and not here is a booth
// charging yesterday's price, so the duplication is made to fail loudly.
func TestPricesMatchTheMarketingCatalogue(t *testing.T) {
	// Located relative to this file, and skipped rather than failed when it is
	// absent: the agent module must stay buildable on its own.
	path := filepath.Join("..", "..", "..", "packages", "content", "src", "verticals", "studio.ts")
	src, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		t.Skip("packages/content is not present; nothing to compare against")
	}
	if err != nil {
		t.Fatalf("read studio.ts: %v", err)
	}

	want := parsePrices(t, string(src))
	if len(want) == 0 {
		t.Fatal("parsed no prices from studio.ts; the drift guard is not guarding anything")
	}

	all, err := catalog.All()
	if err != nil {
		t.Fatalf("catalog: %v", err)
	}
	for _, p := range all {
		got, ok := want[p.ID]
		if !ok {
			t.Errorf("package %q is sold at the booth but is not in studio.ts", p.ID)
			continue
		}
		if got != p.PriceIDR {
			t.Errorf("package %q: booth charges %d, studio.ts says %d", p.ID, p.PriceIDR, got)
		}
	}
}

// parsePrices pulls id/priceIDR pairs out of the TypeScript source.
//
// A regexp rather than a parser because the shape is fixed and generated by
// hand in one file. If this becomes fragile, the answer is a generator that
// emits packages.json, not a cleverer regexp.
func parsePrices(t *testing.T, src string) map[string]int64 {
	t.Helper()

	id := regexp.MustCompile(`id:\s*"([^"]+)"`)
	price := regexp.MustCompile(`priceIDR:\s*unverified\(([0-9_]+)`)

	out := map[string]int64{}
	for _, block := range strings.Split(src, "{")[1:] {
		idm := id.FindStringSubmatch(block)
		pm := price.FindStringSubmatch(block)
		if idm == nil || pm == nil {
			continue
		}
		n, err := strconv.ParseInt(strings.ReplaceAll(pm[1], "_", ""), 10, 64)
		if err != nil {
			t.Fatalf("parse price %q: %v", pm[1], err)
		}
		out[idm[1]] = n
	}
	return out
}
